install:
	cd app/server && npm install
	cd app/client && npm install

seed:
	cd app/server && npm run seed

dev:
	cd app/server && npm start & cd app/client && npm run dev

docker-up:
	docker-compose up --build

docker-down:
	docker-compose down -v
